// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG1CrgwYTDCpbA0JD-WUqwyK2bAIi2XFw',
    appId: '1:1076233817613:android:68cea064f850494aa78f44',
    messagingSenderId: '1076233817613',
    projectId: 'zentracking-13418',
    storageBucket: 'zentracking-13418.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQfVr1AyanIVvE99r3dOCVbZAvE92SirE',
    appId: '1:1076233817613:ios:26275876afdf0da7a78f44',
    messagingSenderId: '1076233817613',
    projectId: 'zentracking-13418',
    storageBucket: 'zentracking-13418.firebasestorage.app',
    androidClientId: '1076233817613-s8smq35re4kaokji94sn42i7r5ots3nd.apps.googleusercontent.com',
    iosClientId: '1076233817613-92qtn6hse8jl94serq5h8d5m0q5pg79c.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

}